# Generated by Django 5.0.6 on 2025-01-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='exp_gy_ref',
            new_name='gy_ref',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='exp_mc_ref',
            new_name='mc_ref',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mk_gy_ref',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mk_mc_ref',
        ),
    ]
