# Generated by Django 5.0.6 on 2025-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_exp_gy_ref_product_gy_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gy_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
