# Generated by Django 5.0.6 on 2025-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_ref_error_product_ref_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_type',
            field=models.CharField(blank=True, choices=[('MARKET', 'Market'), ('EXPRESS', 'Express')], help_text='Type of store: MARKET or EXPRESS.', max_length=7, null=True),
        ),
    ]
